"""Simple SafeLang to C code generator."""

from __future__ import annotations

import re
from typing import List

from .parser import FunctionDef

_TYPE_MAP = {
    "f32": "float",
    "f64": "double",
    "int8": "int8_t",
    "uint8": "uint8_t",
    "int16": "int16_t",
    "uint16": "uint16_t",
    "int32": "int32_t",
    "uint32": "uint32_t",
    "int64": "int64_t",
    "uint64": "uint64_t",
}

_PARAM_RE = re.compile(r"(\w+)\(([^)]+)\)")


def _parse_params(lines: List[str]) -> List[str]:
    params = []
    for ln in lines:
        m = _PARAM_RE.search(ln)
        if not m:
            continue
        typ, name = m.group(1), m.group(2)
        c_typ = _TYPE_MAP.get(typ, "int")
        params.append(f"{c_typ} {name}")
    return params


def generate_c(funcs: List[FunctionDef]) -> str:
    """Generate a very small C translation of ``funcs``."""
    lines = ["// Generated by SafeLang", "#include <stdint.h>", ""]
    for fn in funcs:
        params = _parse_params(fn.consume)
        lines.append(f"/* {fn.name}: @space {fn.space} @time {fn.time} */")
        lines.append(f"void {fn.name}({', '.join(params)}) {{")
        body = fn.body.strip().splitlines()
        for b in body:
            lines.append("    " + b.rstrip())
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


__all__ = ["generate_c"]
