from pathlib import Path

from safelang import parse_functions, generate_c, generate_rust


def _load_example_funcs():
    src = Path(__file__).resolve().parents[1] / "example.slang"
    return parse_functions(src.read_text())


def test_generate_c_contains_clamp_params():
    funcs = _load_example_funcs()
    c_code = generate_c(funcs)
    assert c_code.startswith("// Generated by SafeLang")
    assert "clamp_params" in c_code


def test_generate_rust_contains_clamp_params():
    funcs = _load_example_funcs()
    rust_code = generate_rust(funcs)
    assert "pub fn clamp_params" in rust_code
