name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --files $(git ls-files '*.py') || true
          if ! git diff --quiet; then
            git config user.name 'github-actions'
            git config user.email 'github-actions@github.com'
            git commit -am "chore: format code with black"
            git push
          fi
      - name: Run tests
        run: pytest -v
